/**
 * Function to get the payroll preview from Zeal API.
 *
 * @param {Object} args - Arguments for the preview request.
 * @param {string} args.job_id - The job_id of the Payroll Preview generated by the relevant endpoints.
 * @returns {Promise<Object>} - The result of the payroll preview request.
 */
const executeFunction = async ({ job_id }) => {
  const apiUrl = 'https://api.zeal.com';
  const token = process.env.ZEAL_PUBLIC_API_API_KEY;

  try {
    // Construct the URL with query parameters
    const url = new URL(`${apiUrl}/preview`);
    url.searchParams.append('job_id', job_id);

    // Set up headers for the request
    const headers = {
      'Accept': 'application/json'
    };

    // If a token is provided, add it to the Authorization header
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    // Perform the fetch request
    const response = await fetch(url.toString(), {
      method: 'GET',
      headers
    });

    // Check if the response was successful
    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(JSON.stringify(errorData));
    }

    // Parse and return the response data
    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Error getting payroll preview:', error);
    return {
      error: `An error occurred while getting the payroll preview: ${error instanceof Error ? error.message : JSON.stringify(error)}`
    };
  }
};

/**
 * Tool configuration for getting payroll preview from Zeal API.
 * @type {Object}
 */
const apiTool = {
  function: executeFunction,
  definition: {
    type: 'function',
    function: {
      name: 'get_payroll_preview',
      description: 'Get the payroll preview from Zeal API.',
      parameters: {
        type: 'object',
        properties: {
          job_id: {
            type: 'string',
            description: 'The job_id of the Payroll Preview generated by the relevant endpoints.'
          }
        },
        required: ['job_id']
      }
    }
  }
};

export { apiTool };